export { config as bun } from "./bun.mjs"
export { config as deno } from "./deno.mjs"
export { config as npm } from "./npm.mjs"
// export { config as oro } from "./orogene.mjs"
export { config as pnpm } from "./pnpm.mjs"
export { config as yarn1 } from "./yarn1.mjs"
export { config as yarn3 } from "./yarn3.mjs"
