name: Run On Label

on:
    pull_request:
        types: [labeled]

jobs:
    compare:
        if: ${{ github.event.label.name == 'compare' }}
        uses: "SocketDev/dependency-divergence/.github/workflows/compare.yml@main"
        with:
            managers: "bun,deno,npm,pnpm,yarn1,yarn3"
            cwd: "."

                
